dangerouslyAllowAllBuilds: false
allowBuilds: { esbuild: true, sharp: true, workerd: true }
audit:
  level: high
trustPolicyIgnoreAfter: 129600
trustPolicy: no-downgrade
verifyDepsBeforeRun: error
registry: https://registry.npmjs.org
